#!/usr/bin/env python
# coding: utf-8
import subprocess
import os.path
import ast


FORMAT = "myfile{}.zip" # CHANGEME
DELIMITER = 'e' # CHANGEME WITH DELIMITER CHAR BEFORE BACKUP NUMBER


backup_files = subprocess.check_output(['ls']).split('\n')
backup_files = [f for f in backup_files if f.endswith('.zip')]

print("Found %i backup files." % len(backup_files))

backup_names = [os.path.splitext(f)[0] for f in backup_files]
# We trim the extension
last_name = backup_names[-1]

last_number = ast.literal_eval(last_name.split(DELIMITER)[-1])

print("Last backup was #%i" % last_number)
new_number = last_number + 1
print("New one will be #%i" % new_number)
print(FORMAT.format(last_number+1))
