(when (>= emacs-major-version 24)
  (require 'package)
  (add-to-list
   'package-archives
   '("melpa" . "http://melpa.org/packages/")
   t)
  (package-initialize))
(add-to-list 'load-path "/root/.emacs.d/dockerfile-mode")
(require 'dockerfile-mode)
(add-to-list 'auto-mode-alist '("Dockerfile\\'" . dockerfile-mode))
(add-to-list 'load-path "/root/.emacs.d/neotree")
(require 'neotree)
(global-set-key [f8] 'neotree-toggle)
(global-linum-mode)
(add-to-list 'load-path "/root/.emacs.d/powerline")
(require 'powerline)
(powerline-default-theme)
(add-to-list 'custom-theme-load-path "~/.emacs.d/moe-theme.el/")
(add-to-list 'load-path "/root/.emacs.d/moe-theme")
(require 'auto-complete-config)
(define-key ac-completing-map (kbd "C-n") 'ac-next)
(define-key ac-completing-map (kbd "C-p") 'ac-previous)
(ac-config-default)
(yas-global-mode 1)
(require 'moe-theme)
(load-theme 'moe-dark t)
(moe-dark)
(moe-theme-set-color 'blue)
(require 'saveplace)
(setq-default save-place t)
(defun show-file-name ()
  "Show the full path file name in the minibuffer."
  (interactive)
  (message (buffer-file-name)))
(global-set-key [f7] 'show-file-name) ; Or any other key you want
(global-visual-line-mode t) ; add word-wrap
